------------------------------------------------------------------------------------------------------------------------
-- 1) Роли пользователей (справочник)
drop table if exists public.roles cascade;
CREATE TABLE public.roles(
                      id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "name" varchar(20) NOT NULL UNIQUE,
                      "code_name" varchar(20) NOT NULL UNIQUE
);
-- заполнение справочника
INSERT INTO public.roles(name, code_name)
VALUES ('пользователь', 'ROLE_USER'),
       ('модератор', 'ROLE_MODERATOR'),
       ('администратор', 'ROLE_ADMIN');
------------------------------------------------------------------------------------------------------------------------
-- 2) Виды спотов (справочник)
drop table if exists public.spot_types cascade;
CREATE TABLE public.spot_types(
                             id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar(20) NOT NULL
);
-- заполнение справочника
INSERT INTO public.spot_types(name)
VALUES ('скейтпарк'),
       ('стрит'),
       ('дёрты'),
       ('вёрт'),
       ('bmx-рейсинг'),
       ('флэтленд');
------------------------------------------------------------------------------------------------------------------------
-- 3) Виды спорта (справочник)
drop table if exists public.sport_types cascade;
CREATE TABLE public.sport_types(
                                  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "name" varchar(20) NOT NULL,
                                  transport_name varchar(20) NOT NULL
);
-- заполнение справочника
INSERT INTO public.sport_types(name, transport_name)
VALUES ('bmx-фристайл', 'bmx'),
       ('скейтбординг', 'скейтборд'),
       ('самокат-фристайл', 'самокат'),
       ('горный велоспорт', 'MTB'),
       ('роллер-спорт', 'ролики'),
       ('лыжный спорт', 'лыжи'),
       ('сноубординг', 'сноуборд');
------------------------------------------------------------------------------------------------------------------------
-- 4) Тип помещения как пространства для катания (справочник)
drop table if exists public.space_types cascade;
CREATE TABLE public.space_types(
                                   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "name" varchar(20) NOT NULL
);
-- заполнение справочника
INSERT INTO public.space_types(name)
VALUES ('крытое помещение'),
       ('под навесом'),
       ('под открытым небом');
------------------------------------------------------------------------------------------------------------------------
-- Пользователи
drop table if exists public.users cascade;
CREATE TABLE public.users(
                       id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       "name" varchar(30) NOT NULL UNIQUE,
                       email varchar(50) NOT NULL UNIQUE,
                       pass_hash varchar(256) NOT NULL,
                       phone_number varchar(15) NOT NULL,
                       birthday date NOT NULL,
                       reg_date date NOT NULL,
                        -- удалять роли и изменять их id запрещено
                       role_id int NOT NULL DEFAULT 1 REFERENCES public.roles (id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
------------------------------------------------------------------------------------------------------------------------
-- Споты
drop table if exists public.spots cascade;
CREATE TABLE public.spots(
                             id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar(50) NOT NULL,
                             -- latitude coordinate (координата широты)
                             lat FLOAT NOT NULL,
                             -- longitude coordinate (координата долготы)
                             lon FLOAT NOT NULL,
                             accepted BOOLEAN NOT NULL DEFAULT FALSE,
                             adding_date date NOT NULL,
                             updating_date date NOT NULL,
                             "desc" varchar(300) NOT NULL,
                             spot_type_id int NOT NULL REFERENCES public.spot_types (id)
                                 ON UPDATE CASCADE ON DELETE RESTRICT,
                             space_type_id int NOT NULL REFERENCES public.space_types (id)
                                 ON UPDATE CASCADE ON DELETE RESTRICT,
                             moder_id int DEFAULT NULL REFERENCES public.users (id)
                                 ON UPDATE CASCADE ON DELETE SET NULL

);
------------------------------------------------------------------------------------------------------------------------
-- Информация об изображениях (спотов, пользователей, )
drop table if exists public.image_info cascade;
CREATE TABLE public.image_info(
                             id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             orig_name varchar(255) NOT NULL,
                             gen_name varchar(100) NOT NULL,
                             size integer NOT NULL,
                             upload_date date NOT NULL,
                             spot_id int DEFAULT NULL REFERENCES public.spots (id)
                                 ON UPDATE CASCADE ON DELETE CASCADE,
                             user_id int DEFAULT NULL REFERENCES public.users (id)
                                 ON UPDATE CASCADE ON DELETE CASCADE
);
------------------------------------------------------------------------------------------------------------------------
-- Комментарии
drop table if exists public.comments cascade;
CREATE TABLE public.comments(
                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "text" varchar(100) NOT NULL,
                            upload_date date NOT NULL,
                            spot_id int NOT NULL REFERENCES public.spots (id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
                            user_id int NOT NULL REFERENCES public.users (id)
                              ON UPDATE CASCADE ON DELETE CASCADE
);
------------------------------------------------------------------------------------------------------------------------
-- Промежуточная таблица спот-пользователь
drop table if exists public.spots_users cascade;
CREATE TABLE public.spots_users(
                               favorite BOOLEAN NOT NULL DEFAULT FALSE,
                               liked BOOLEAN NOT NULL DEFAULT FALSE,
                               spot_id int NOT NULL REFERENCES public.spots (id)
                                   ON UPDATE CASCADE ON DELETE CASCADE,
                               user_id int REFERENCES public.users (id)
                                   ON UPDATE CASCADE ON DELETE SET NULL,
                               PRIMARY KEY (spot_id, user_id)
);
------------------------------------------------------------------------------------------------------------------------